### ISSUE TITLE
Saved Netplans missing ':' after interface name

### ISSUE THREAD

**Issue by OliverSimpsonTechex** [Simmotipo/nptui#10]
**Effected Versions**
All

**Current Behaviour**
When saving netplans, the line containing ethernet interface name is missing its colon.

**Excepted Behaviour**
Should have colon

Example::

```
network:
  version: 2
  ethernets:
    eno8303
      dhcp4: no
```

Note no : on the eno8303 line
