### ISSUE TITLE
When loading nptui-generated plans, default gateways are not recognised

### ISSUE THREAD

**Issue by Simmotipo** [Simmotipo/nptui#12]
**Effected Versions**
At least 1.3

**Current Behaviour**
- Create a plan with nptui with dhcp4 no, and add a gateway
- Save, exit, close, reopen + load
- Interface does not have a gateway listed, but does have a default route in custom routes

**Expected Behaviour**
- Interface should have the default gateway listed

Example file:
```
network:
  version: 2
  ethernets:
    eno8303:
      dhcp4: no
      addresses:
        - 192.168.0.2/24
      nameservers:
        addresses: []
      routes:
        - to:  default
          via: 192.168.0.1
          metric: 100
```

![Image](https://github.com/user-attachments/assets/56a20880-68ce-454c-9110-1fad4834e0a2)

![Image](https://github.com/user-attachments/assets/72fa671c-50d6-4d02-b462-8f383c73954d)
