### ISSUE TITLE
Netplan File Not Loaded Correctly

### ISSUE THREAD

**Issue by Simmotipo** [Simmotipo/nptui#17]
Trying to load this file (at /etc/netplan/25-nptui.yaml), with perms chmod 600, results in only eth0 being picked up, and set as dhcp...

```
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 172.26.228.91/20
      nameservers:
        addresses: [8.8.8.8,10.12.3.12]
      routes:
        - to: default
          via: 172.26.224.1
    lo:
      dhcp4: yes
```
